# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:staticallyGreet
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:dynamicallyGreet
        name: ~

acme_sylius_example_generate_referral_coupon:
    path: /generate-referral-coupon
    defaults:
        _controller: Acme\SyliusExamplePlugin\Controller\ReferralPromotionCouponController:generateAction

acme_sylius_example_search:
    path: /search-products
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: "@AcmeSyliusExamplePlugin/search.html.twig"
            grid: acme_sylius_example_product_search
